version: "3.8"  # Use the appropriate version (adjust if needed)

services:
  web:
    build: .  # Build the Docker image using the current directory (where the Dockerfile is)
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container (adjust as needed)

